name: GitHub Classroom Workflow

on: [push]

jobs:
    build:
        permissions: write-all
        name: Autograding
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v2
          - name: Prepare autograder
            run: cp .github/autograder.sh autograder.sh
          - name: Compile submission
            run: make clean && make
          - name: Run autograder
            run: ./autograder.sh
          - uses: education/autograding@v1
