name: GitHub Classroom Workflow

on: [push]

jobs:
    build:
        permissions: write-all
        name: Autograding
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v2
          - name: Prepare autograde
            run: cp .github/autograde.sh autograde.sh
          - name: Compile submission
            run: make clean && make
          - name: Run autograde
            run: ./autograde.sh
          - uses: education/autograding@v1
